export type CitySeoPage = {
  slug: string;
  name: string;
  published: false;
  es: { title: string; description: string };
  en: { title: string; description: string };
};

// Editorial scaffold only. These pages remain noindex and out of the sitemap until approved city copy is supplied.
export const CITY_SEO_PAGES: CitySeoPage[] = [
  { slug: "san-pedro-sula", name: "San Pedro Sula", published: false, es: { title: "viatour | Agencia de viajes en San Pedro Sula", description: "Agencia de viajes en San Pedro Sula para planificar vuelos, hoteles y viajes a la medida desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in San Pedro Sula", description: "Travel agency in San Pedro Sula for flights, hotels and custom trips from Honduras with personal guidance from viatour." } },
  { slug: "tegucigalpa", name: "Tegucigalpa", published: false, es: { title: "viatour | Agencia de viajes en Tegucigalpa", description: "Agencia de viajes en Tegucigalpa para organizar vuelos, hoteles y viajes personalizados desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in Tegucigalpa", description: "Travel agency in Tegucigalpa for flights, hotels and personalized trips from Honduras with personal guidance from viatour." } },
  { slug: "danli", name: "Danlí", published: false, es: { title: "viatour | Agencia de viajes en Danlí", description: "Agencia de viajes en Danlí para consultar vuelos, hoteles y opciones de viaje a la medida desde Honduras con viatour." }, en: { title: "viatour | Travel agency in Danlí", description: "Travel agency in Danlí for flights, hotels and custom travel options from Honduras with personal guidance from viatour." } },
  { slug: "roatan", name: "Roatán", published: false, es: { title: "viatour | Agencia de viajes en Roatán", description: "Agencia de viajes en Roatán para planificar vuelos, hoteles y experiencias personalizadas desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in Roatán", description: "Travel agency in Roatán for planning flights, hotels and personalized experiences from Honduras with guidance from viatour." } },
  { slug: "la-ceiba", name: "La Ceiba", published: false, es: { title: "viatour | Agencia de viajes en La Ceiba", description: "Agencia de viajes en La Ceiba para organizar vuelos, hoteles y viajes personalizados desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in La Ceiba", description: "Travel agency in La Ceiba for flights, hotels and personalized trips from Honduras with personal guidance from viatour." } },
  { slug: "el-progreso", name: "El Progreso", published: false, es: { title: "viatour | Agencia de viajes en El Progreso", description: "Agencia de viajes en El Progreso para consultar vuelos, hoteles y viajes a la medida desde Honduras con acompañamiento de viatour." }, en: { title: "viatour | Travel agency in El Progreso", description: "Travel agency in El Progreso for flights, hotels and custom trips from Honduras with personal guidance from viatour." } },
  { slug: "choloma", name: "Choloma", published: false, es: { title: "viatour | Agencia de viajes en Choloma", description: "Agencia de viajes en Choloma para planificar vuelos, hoteles y opciones personalizadas de viaje desde Honduras con viatour." }, en: { title: "viatour | Travel agency in Choloma", description: "Travel agency in Choloma for flights, hotels and personalized travel options from Honduras with guidance from viatour." } },
  { slug: "comayagua", name: "Comayagua", published: false, es: { title: "viatour | Agencia de viajes en Comayagua", description: "Agencia de viajes en Comayagua para organizar vuelos, hoteles y viajes personalizados desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in Comayagua", description: "Travel agency in Comayagua for flights, hotels and personalized trips from Honduras with personal guidance from viatour." } },
  { slug: "villanueva", name: "Villanueva", published: false, es: { title: "viatour | Agencia de viajes en Villanueva", description: "Agencia de viajes en Villanueva para consultar vuelos, hoteles y viajes a la medida desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in Villanueva", description: "Travel agency in Villanueva for flights, hotels and custom trips from Honduras with personal guidance from viatour." } },
  { slug: "puerto-cortes", name: "Puerto Cortés", published: false, es: { title: "viatour | Agencia de viajes en Puerto Cortés", description: "Agencia de viajes en Puerto Cortés para planificar vuelos, hoteles y viajes personalizados desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in Puerto Cortés", description: "Travel agency in Puerto Cortés for planning flights, hotels and personalized trips from Honduras with guidance from viatour." } },
  { slug: "choluteca", name: "Choluteca", published: false, es: { title: "viatour | Agencia de viajes en Choluteca", description: "Agencia de viajes en Choluteca para organizar vuelos, hoteles y viajes a la medida desde Honduras con acompañamiento de viatour." }, en: { title: "viatour | Travel agency in Choluteca", description: "Travel agency in Choluteca for flights, hotels and custom trips from Honduras with personal guidance from viatour." } },
  { slug: "siguatepeque", name: "Siguatepeque", published: false, es: { title: "viatour | Agencia de viajes en Siguatepeque", description: "Agencia de viajes en Siguatepeque para consultar vuelos, hoteles y opciones de viaje desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in Siguatepeque", description: "Travel agency in Siguatepeque for flights, hotels and travel options from Honduras with personal guidance from viatour." } },
  { slug: "santa-rosa-de-copan", name: "Santa Rosa de Copán", published: false, es: { title: "viatour | Agencia de viajes en Santa Rosa de Copán", description: "Agencia de viajes en Santa Rosa de Copán para planificar vuelos, hoteles y viajes personalizados desde Honduras con viatour." }, en: { title: "viatour | Travel agency in Santa Rosa de Copán", description: "Travel agency in Santa Rosa de Copán for planning flights, hotels and personalized trips from Honduras with viatour." } },
  { slug: "juticalpa", name: "Juticalpa", published: false, es: { title: "viatour | Agencia de viajes en Juticalpa", description: "Agencia de viajes en Juticalpa para organizar vuelos, hoteles y viajes a la medida desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in Juticalpa", description: "Travel agency in Juticalpa for flights, hotels and custom trips from Honduras with personal guidance from viatour." } },
  { slug: "tela", name: "Tela", published: false, es: { title: "viatour | Agencia de viajes en Tela", description: "Agencia de viajes en Tela para consultar vuelos, hoteles y viajes personalizados desde Honduras con asesoría de viatour." }, en: { title: "viatour | Travel agency in Tela", description: "Travel agency in Tela for flights, hotels and personalized trips from Honduras with personal guidance from viatour." } },
];

export function getCitySeoPage(slug: string) {
  return CITY_SEO_PAGES.find(page => page.slug === slug) || null;
}
