export const legalContentEn = {
  terminos: { title: "Terms and Conditions", sections: [
    ["1. Identification", "This website, miviatour.com, is operated by viatour (legal name Viatour, “viatour”, “we”, “us”), with operations in San Pedro Sula, Honduras. You can contact us at soporte@miviatour.com or on WhatsApp at +504 8866-8704."],
    ["2. What we do", "viatour is a travel advice and intermediary service. We help you plan and arrange flights, hotels, packages and custom trips departing from Honduras. We are not an airline, hotel or tour operator: we coordinate your trip with external providers. This website does not process payments or issue bookings automatically; every quote and booking is coordinated personally, primarily through WhatsApp."],
    ["3. Relationship with IATA", "viatour operates in affiliation with a host agency accredited by IATA (International Air Transport Association). Ticket issuance and air transport reservations are made through that host agency’s IATA accreditation; viatour acts as a sales intermediary. IATA marks and logo remain the property of IATA and, when shown on this website, identify this affiliation only and do not represent an independent accreditation of viatour."],
    ["4. Quotes and prices", "Prices shown on the website are reference prices and may change according to availability, dates, season, taxes and provider conditions at the time of confirmation. Your advisor confirms the final price before any payment."],
    ["5. Booking process", "You send us a request through the form or WhatsApp; an advisor prepares options; once you accept, the details and final price are confirmed; payment is then made to issue the booking with the relevant provider."],
    ["6. Payments and deposits", "Card and bank-transfer payments are coordinated directly with your advisor. We do not request or store complete card details through the website. If a booking requires a deposit to begin the process, your advisor will explain the amount and conditions before you pay. We issue a receipt for payments received."],
    ["7. Traveller responsibility — documentation", "Each traveller is responsible for having valid travel documents, including a current passport, visas and health or transit requirements. We are glad to guide you, but each country sets its own requirements. We recommend checking the Travel Requirements section of this website and the relevant authorities. viatour is not responsible for denied boarding or entry resulting from incomplete documentation."],
    ["8. External providers", "Transport, accommodation and tour services are provided by third parties and are subject to their own terms, rates and policies. viatour acts as an intermediary and does not control those services."],
    ["9. Changes and cancellations", "These are governed by the Cancellation Policy and by each service provider’s conditions."],
    ["10. Limitation of liability", "To the extent permitted by law, viatour is not responsible for indirect damages arising from acts or omissions of external providers, unforeseen events or force majeure. Our liability is limited to the value of the advice services provided by viatour."],
    ["11. Intellectual property", "viatour’s brand, texts and original images may not be used without authorization."],
    ["12. Applicable law", "These terms are governed by the laws of the Republic of Honduras. Any dispute will be submitted to the courts of San Pedro Sula, Honduras."],
    ["13. Changes to these terms", "We may update these terms; the current version will always be published on this page."],
    ["14. Contact", "soporte@miviatour.com."]
  ] },
  privacidad: { title: "Privacy Policy", sections: [["1. Responsible party", "viatour (San Pedro Sula, Honduras). Privacy contact: soporte@miviatour.com."], ["2. Data we collect", "Data you provide in quote, contact, review and subscription forms: name, email, phone where applicable, and trip details such as origin, destination, dates, travellers and notes. Reviews require an email to validate the review; your email is not published. We also collect technical and usage data through cookies and analytics tools, only with your consent."], ["3. How we use it", "To answer your requests, prepare quotes, manage bookings with providers, send information you requested, moderate and publish reviews, and—with your consent—send travel ideas and measure website use."], ["4. Legal basis and consent", "We process your data with your consent and to handle your request. You may withdraw consent at any time."], ["5. Where it is stored", "Your data is stored securely in our database. viatour’s team accesses it to assist you."], ["6. Who we share it with", "Only with providers needed to arrange the service you request, such as airlines or hotels, and with the communication and analytics tools we use. Analytics tools are used only if you accept the relevant cookies. We do not sell your data."], ["7. Cookies and analytics", "We use necessary cookies for website operation and, with your consent, analytics and marketing cookies. See the Cookie Policy."], ["8. Retention", "We keep your data as long as needed to assist you and meet legal obligations; afterwards we delete or anonymize it."], ["9. Your rights", "You may request access, correction or deletion of your data, and unsubscribe from communications, by writing to soporte@miviatour.com."], ["10. Security", "We apply reasonable measures to protect your information. No system is completely infallible, but we work to keep your data safe."], ["11. Changes", "We will publish updates to this policy here."]] },
  cancelaciones: { title: "Cancellation Policy", sections: [["1. Before confirmation", "Quotes are reference information and do not constitute a booking. There is no charge until you accept an option and make a payment."], ["2. Deposits", "If a booking requires a deposit to begin the process, your advisor will explain the amount and conditions before you pay, including whether it is refundable where applicable."], ["3. After confirmation", "Once a booking is issued, changes, cancellations and refunds are governed by each service provider’s policies. Some fares are non-refundable or allow changes only with a penalty; your advisor will explain the specific conditions before you pay."], ["4. Requesting a change or cancellation", "Write to us on WhatsApp (+504 8866-8704) or at soporte@miviatour.com with your booking details. We will manage your request with the relevant provider."], ["5. Refunds", "Where applicable, refunds are processed according to the provider’s and payment method’s timelines and conditions. Provider administrative fees may apply."], ["6. Force majeure", "For events outside our control, such as weather, closures or official measures, the provider’s policies apply; we will accompany you while alternatives are managed."]] },
  cookies: { title: "Cookie Policy", sections: [["1. What they are", "Small files stored on your device so the website can work and we can understand how it is used."], ["2. Categories we use", "Necessary: essential for website operation and security, always active. Analytics: help us understand how the website is used, only with your consent. Marketing: help us measure and improve campaigns, only with your consent."], ["3. Your control", "When you enter the website, a notice lets you accept or reject non-essential cookies. We do not activate analytics or marketing until you accept. You can change your decision at any time."], ["4. Changes", "We will update this policy if the tools we use change."]] }
} as const;
