import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeSanitize from 'rehype-sanitize';
function load(file,deps={}){const exports={};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;vm.runInNewContext(code,{exports,require:n=>deps[n],URL,FormData,Date,Number,Uint8Array,TextDecoder,File,crypto,process});return exports;}
const utils=load('src/lib/blog-utils.ts');const validation=load('src/lib/blog-validation.ts',{'./blog-utils':utils});
function form(){const f=new FormData();for(const [k,v]of Object.entries({table:'blog_posts',titulo:'Prueba técnica',slug:'prueba-tecnica',categoria:'Prueba',tipo:'guia',extracto:'Prueba t?cnica',cuerpo:'## Encabezado',orden:'0'}))f.set(k,v);return f;}
test('draft defaults, slug, type, date and bucket validation',()=>{const f=form();assert.equal(validation.validateBlog(f).values.publicado,false);assert.equal(utils.suggestSlug('Guía de Panamá'),'guia-de-panama');f.set('publicado','on');assert.ok(validation.validateBlog(f).error);f.set('publicado_en','2026-02-30');assert.ok(validation.validateBlog(f).error);f.set('publicado_en','2026-09-17');assert.equal(validation.validateBlog(f).values.publicado,true);f.set('cover_url','https://example.com/image.jpg');assert.ok(validation.validateBlog(f).error);f.set('cover_url','');f.set('slug','Invalid Slug');assert.ok(validation.validateBlog(f).error);});
test('blog create/edit/publish/delete use authorized session and invalidate slugs',async()=>{const paths=[];const writes=[];const id='12345678-1234-1234-1234-123456789abc';const mutation=(operation,values)=>{writes.push({operation,values});return {eq:()=>({select:()=>({single:async()=>({data:{id}})})}),select:()=>({single:async()=>({data:{id}})})};};const client={from:table=>{assert.equal(table,'blog_posts');return {select:()=>({eq:()=>({single:async()=>({data:{slug:'anterior'}}),maybeSingle:async()=>({data:null})})}),insert:v=>mutation('create',v),update:v=>mutation('edit',v),delete:()=>mutation('delete')};}};const api=load('src/app/admin/actions.ts',{'@/lib/blog-validation':validation,'@/lib/admin':{requireAdmin:async()=>({client})},'next/cache':{revalidatePath:p=>paths.push(p)}});const f=form();assert.ok((await api.save({},f)).success);assert.equal(writes[0].values.publicado,false);f.set('id',id);f.set('publicado','on');f.set('publicado_en','2026-09-17');assert.ok((await api.save({},f)).success);assert.equal(writes[1].values.publicado,true);assert.ok(paths.includes('/blog/anterior'));assert.ok(paths.includes('/blog/prueba-tecnica'));assert.ok(paths.includes('/sitemap.xml'));f.set('operation','delete');assert.ok((await api.save({},f)).success);assert.equal(writes[2].operation,'delete');});
test('Markdown sanitizes scripts, event handlers and dangerous URLs and limits headings',async()=>{const jsx=await import('react/jsx-runtime');const {Markdown}=load('src/components/blog/markdown.tsx',{'react/jsx-runtime':jsx,'react-markdown':{default:ReactMarkdown},'remark-gfm':{default:remarkGfm},'rehype-sanitize':{default:rehypeSanitize}});const html=renderToStaticMarkup(React.createElement(Markdown,null,'# T?tulo\n\n## Secci?n\n\n- Uno\n- Dos\n\n> Texto\n\n[Seguro](https://example.com)\n\n[Malo](javascript:alert(1))\n\n<script>alert(1)</script><img src=x onerror=alert(1)>')); assert.ok(html.includes('<h2'));assert.ok(html.includes('<ul>'));assert.ok(html.includes('<blockquote>'));assert.ok(!html.includes('<h1'));assert.ok(!html.includes('<script'));assert.ok(!html.includes('onerror'));assert.ok(!html.includes('javascript:'));});
test('cover upload uses authenticated storage, validates bytes and denies non-admins',async()=>{let uploads=0;let allowed=true;const client={auth:{getUser:async()=>({data:{user:{id:'admin'}}})},rpc:async()=>({data:allowed}),storage:{from:bucket=>{assert.equal(bucket,'blog-images');return {upload:async(path,bytes,options)=>{uploads++;assert.ok(path.startsWith('admin/'));assert.equal(options.contentType,'image/png');return {};},getPublicUrl:path=>({data:{publicUrl:'https://project.supabase.co/storage/v1/object/public/blog-images/'+path}})};}}};const api=load('src/app/api/admin/blog-images/route.ts',{'@/lib/supabase/server':{createClient:async()=>client},'next/server':{NextResponse:{json:(data,options)=>Response.json(data,options)}}});const request=(bytes,type)=>{const f=new FormData();f.set('file',new File([new Uint8Array(bytes)],'test.png',{type}));return new Request('https://example.com',{method:'POST',body:f});};assert.equal((await api.POST(request([1,2,3],'image/png'))).status,400);const good=await api.POST(request([137,80,78,71,13,10,26,10],'image/png'));assert.equal(good.status,200);assert.ok((await good.json()).url.includes('/blog-images/'));allowed=false;assert.equal((await api.POST(request([137,80,78,71,13,10,26,10],'image/png'))).status,403);assert.equal(uploads,1);});
