import assert from 'node:assert/strict';
const origin=process.env.SMOKE_ORIGIN||'http://localhost:3010';
const sitemap=await(await fetch(origin+'/sitemap.xml')).text();assert.ok(sitemap.includes('<urlset'));assert.ok(!/\/admin|\/api/.test(sitemap));
const robots=await(await fetch(origin+'/robots.txt')).text();assert.ok(robots.includes('Disallow: /admin'));assert.ok(robots.includes('Disallow: /api'));assert.ok(robots.includes('https://miviatour.com/sitemap.xml'));
const routes=[...new Set([...sitemap.matchAll(/<loc>https:\/\/miviatour.com([^<]*)<\/loc>/g)].map(m=>m[1]||'/'))];
for(const route of ['/legales/terminos','/legales/privacidad','/legales/cancelaciones','/legales/cookies'])routes.push(route);
const titles=new Set(),descriptions=new Set();let schemaCount=0;
for(const route of routes){const r=await fetch(origin+route,{headers:{'user-agent':'Twitterbot'}});assert.equal(r.status,200,route);const html=await r.text();const title=html.match(/<title>(.*?)<\/title>/)?.[1];const description=html.match(/<meta name="description" content="([^"]*)"/)?.[1];assert.ok(title,route);assert.ok(description,route);assert.ok(!titles.has(title),'duplicate title '+route);assert.ok(!descriptions.has(description),'duplicate description '+route);titles.add(title);descriptions.add(description);assert.equal((html.match(/<h1\b/g)||[]).length,1,route);assert.ok(html.includes('rel="canonical" href="https://miviatour.com'+(route==='/'?'':route)+'"'),route+' canonical');for(const tag of ['og:title','og:description','og:image','twitter:card','twitter:title','twitter:description','twitter:image'])assert.ok(html.includes('"'+tag+'"'),route+' '+tag);assert.ok(!/<script[^>]*src="https:\/\/(www.googletagmanager.com|connect.facebook.net)/.test(html));for(const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){const schema=JSON.parse(m[1]);schemaCount++;const nodes=schema['@graph']||[schema];for(const node of nodes){assert.ok(!node.awards&&!node.memberOf&&!node.hasCredential);if(node['@type']==='Product'&&node.offers){assert.ok(node.offers.price>0);assert.ok(node.offers.priceCurrency)}if(node.aggregateRating)assert.ok(node.aggregateRating.reviewCount>0)}}console.log(route,title.length,description.length)}
for(const route of ['/og','/apple-icon','/icon.svg']){const r=await fetch(origin+route);assert.equal(r.status,200,route);assert.ok(r.headers.get('content-type').startsWith('image/'),route)}
console.log('PASS',routes.length,'public routes, unique metadata, H1s, canonicals, social tags,',schemaCount,'JSON-LD blocks, sitemap/robots, branded image endpoints; no vendor script in SSR.');
