import { Suspense } from "react";
import { useTranslations } from "next-intl";
import { getTranslations } from "next-intl/server";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import { Link } from "@/i18n/navigation";
import { ArrowUpRight, BookOpen, MessageSquare, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { getBlogPosts } from "@/lib/blog";
import { BlogCard } from "@/components/blog/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { getFAQs, type FAQ } from "@/lib/faqs";
import { getReviewSummary } from "@/lib/reviews";
import { RatingSummary } from "@/components/reviews/display";
import { getPackages } from "@/lib/packages";
import { PackageGrid } from "@/components/packages/package-card";
import { getDestinations } from "@/lib/destinations";
import { homeDestinations } from "@/lib/home-destinations";
import { FlightTool } from "@/components/home/flight-tool";
import { HeroBackdrop } from "@/components/home/hero-backdrop";
import { QuoteButton } from "@/components/home/quote-button";

export { DiscoverTeaser } from "@/components/home/discover-teaser";
export { SocialReels } from "@/components/home/social-reels";
export { Services } from "@/components/home/services";
export { WhyViatour } from "@/components/home/why-viatour";

async function FeaturedDestinationData() {
  const t = await getTranslations();
  let destinationSlugs = new Set<string>();
  try { destinationSlugs = new Set((await getDestinations()).map(item => item.slug)); } catch { /* Local launch catalogue remains useful when the CMS is unavailable. */ }
  return <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{homeDestinations.map(destination => { const href = destinationSlugs.has(destination.slug) ? `/destinos/${destination.slug}` : "/destinos"; return <Link key={destination.slug} href={href} className="media-card group block overflow-hidden rounded-card border border-line bg-canvas shadow-sm transition-shadow duration-(--duration-fast) ease-out hover:shadow-md"><div className="relative aspect-[4/3] overflow-hidden bg-surface"><Image src={destination.image} alt={t("home.photoAlt", { name: destination.nombre })} fill sizes="(max-width: 639px) calc(100vw - 32px), (max-width: 1023px) calc((100vw - 72px) / 2), (max-width: 1199px) calc((100vw - 96px) / 3), 368px" className="object-cover" /></div><div className="flex items-center justify-between gap-4 p-6"><h3 className="t-h3">{destination.nombre}</h3><ArrowUpRight size={24} strokeWidth={1.75} className="shrink-0 text-brand" aria-hidden="true" /></div></Link>; })}</div>;
}

export function Hero() { const t = useTranslations(); return <HeroBackdrop><div className="container-site"><FlightTool compact heading={<div className="space-y-3 border-b border-line p-4 sm:p-8"><h1 id="hero-title" className="t-display max-w-3xl">{t("home.heroTitle")}</h1><p className="t-body text-ink-soft">{t("home.assistance")}</p></div>} /></div></HeroBackdrop>; }

export function HowItWorks() { const t = useTranslations(); const steps = [{ number: "01", icon: MessageSquare, title: t("home.how1Title"), body: t("home.how1Body") }, { number: "02", icon: SlidersHorizontal, title: t("home.how2Title"), body: t("home.how2Body") }, { number: "03", icon: ShieldCheck, title: t("home.how3Title"), body: t("home.how3Body") }]; return <section className="border-y border-line bg-surface py-14 sm:py-24" aria-labelledby="how-title"><div className="container-site"><div className="mb-12 max-w-2xl space-y-4"><h2 id="how-title" className="t-h2">{t("home.howTitle")}</h2><p className="t-body-lg text-ink-soft">{t("home.howIntro")}</p></div><div className="grid gap-6 md:grid-cols-3">{steps.map(({ number, icon: Icon, title, body }) => <article key={title} className="rounded-card border border-line bg-canvas p-6 shadow-sm"><div className="mb-8 flex items-center justify-between"><Icon size={28} strokeWidth={1.75} className="text-brand" aria-hidden="true" /><span className="t-small text-ink-soft">{number}</span></div><h3 className="t-h3 mb-4">{title}</h3><p className="t-body text-ink-soft">{body}</p></article>)}</div></div></section>; }

export function FeaturedDestinations() { const t = useTranslations(); return <section className="container-site py-14 sm:py-24" aria-labelledby="destinations-title"><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="space-y-4"><h2 id="destinations-title" className="t-h2">{t("common.destinations")}</h2><p className="t-body-lg measure text-ink-soft">{t("home.destinationsIntro")}</p></div><Link href="/destinos" className="t-small inline-flex items-center gap-2 self-start text-brand underline underline-offset-4 sm:self-auto">{t("home.allDestinations")}<ArrowUpRight size={16} aria-hidden="true" /></Link></div><Suspense fallback={<DestinationCardSkeletons />}><FeaturedDestinationData /></Suspense></section>; }
function DestinationCardSkeletons() { const t = useTranslations(); return <div role="status" aria-label={t("common.loading")} className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3"><span className="sr-only">{t("common.loading")}</span>{homeDestinations.slice(0, 3).map(destination => <div key={destination.slug} aria-hidden="true" className="overflow-hidden rounded-card border border-line bg-canvas motion-safe:animate-pulse"><div className="aspect-[4/3] bg-surface" /><div className="h-8 bg-canvas p-6" /></div>)}</div>; }

export function FeaturedPackages() { return <Suspense fallback={null}><FeaturedPackageData /></Suspense>; }
async function FeaturedPackageData() { const t = await getTranslations(); let items; try { items = await getPackages(true); } catch { return null; } if (!items.length) return null; return <section className="border-y border-line bg-surface py-14 sm:py-24" aria-labelledby="packages-title"><div className="container-site"><div className="mb-8 space-y-4"><h2 id="packages-title" className="t-h2">{t("home.featuredPackages")}</h2><p className="t-body-lg measure text-ink-soft">{t("home.packagesIntro")}</p></div><PackageGrid items={items} /><Link href="/paquetes" className="t-small mt-8 inline-flex items-center gap-2 text-brand underline underline-offset-4">{t("common.packages")}<ArrowUpRight size={16} aria-hidden="true" /></Link></div></section>; }

export function ReviewsTeaser() { return <Suspense fallback={null}><ReviewTeaserData /></Suspense>; }
async function ReviewTeaserData() { const t = await getTranslations(); let summary; try { summary = await getReviewSummary(); } catch { return null; } if (!summary.total) return <section className="bg-surface py-14 sm:py-24" aria-labelledby="reviews-title"><div className="container-site grid gap-8 md:grid-cols-2 md:items-center"><div className="space-y-4"><h2 id="reviews-title" className="t-h2">{t("common.reviews")}</h2><p className="t-body-lg text-ink-soft">{t("home.reviewsIntro")}</p><Link href="/opiniones/nueva" className="t-small inline-flex items-center gap-2 text-brand underline underline-offset-4">{t("home.shareReview")}<ArrowUpRight size={16} aria-hidden="true" /></Link></div><div className="rounded-panel border border-line bg-canvas p-8 shadow-sm"><p className="t-body">{t("home.noReviews")}</p></div></div></section>; return <section className="bg-surface py-14 sm:py-24" aria-labelledby="reviews-title"><div className="container-site grid gap-8 md:grid-cols-2 md:items-center"><div className="space-y-4"><h2 id="reviews-title" className="t-h2">{t("common.reviews")}</h2><p className="t-body-lg text-ink-soft">{t("home.reviewsIntro")}</p><Link href="/opiniones" className="t-small inline-flex items-center gap-2 text-brand underline underline-offset-4">{t("common.reviews")}<ArrowUpRight size={16} aria-hidden="true" /></Link></div><div className="rounded-panel border border-line bg-canvas p-8 shadow-sm"><RatingSummary summary={summary} /></div></div></section>; }

export function TravelGuides() { return <Suspense fallback={null}><TravelGuidesContent /></Suspense>; }
async function TravelGuidesContent() { const t = await getTranslations(); let posts; try { posts = await getBlogPosts(); } catch { return null; } if (!posts.length) return null; return <section className="container-site py-14 sm:py-24" aria-labelledby="guides-title"><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="space-y-4"><div className="flex items-center gap-3"><BookOpen size={24} strokeWidth={1.75} className="text-brand" aria-hidden="true" /><h2 id="guides-title" className="t-h2">{t("home.guidesTitle")}</h2></div><p className="t-body-lg measure text-ink-soft">{t("home.guidesIntro")}</p></div><Link href="/blog" className="t-small inline-flex items-center gap-2 self-start text-brand underline underline-offset-4 sm:self-auto">{t("home.allGuides")}<ArrowUpRight size={16} aria-hidden="true" /></Link></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{posts.slice(0, 3).map(post => <BlogCard key={post.id} post={post} />)}</div></section>; }

export function FrequentlyAskedQuestions() { return <Suspense fallback={null}><FrequentlyAskedQuestionsContent /></Suspense>; }
async function FrequentlyAskedQuestionsContent() { const t = await getTranslations(); let faqs: FAQ[] = []; try { faqs = await getFAQs(); } catch { /* Keep the FAQ entry point visible while content is unavailable. */ } const visible = faqs.slice(0, 5); const schema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: visible.map(faq => ({ "@type": "Question", name: faq.pregunta, acceptedAnswer: { "@type": "Answer", text: faq.respuesta } })) }; return <section className="border-y border-line bg-surface py-14 sm:py-24" aria-labelledby="faq-title"><div className="container-site grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)] lg:gap-16"><div className="space-y-4"><h2 id="faq-title" className="t-h2">{t("common.faq")}</h2><p className="t-body-lg text-ink-soft">{t("home.faqIntro")}</p><Link href="/preguntas-frecuentes" className="t-small inline-flex min-h-11 items-center gap-2 text-brand underline underline-offset-4">{t("home.allQuestions")}<ArrowUpRight size={16} aria-hidden="true" /></Link></div>{visible.length > 0 && <Accordion type="single" collapsible className="w-full">{visible.map(faq => <AccordionItem key={faq.id} value={faq.id}><AccordionTrigger>{faq.pregunta}</AccordionTrigger><AccordionContent>{faq.respuesta}</AccordionContent></AccordionItem>)}</Accordion>}</div>{visible.length > 0 && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />}</section>; }

export function TravelRequirements() { const t = useTranslations(); return <section className="container-site py-14 sm:py-24" aria-labelledby="requirements-title"><div className="space-y-6"><h2 id="requirements-title" className="t-h2">{t("common.requirements")}</h2><p className="t-body-lg measure text-ink-soft">{t("home.requirementsIntro")}</p><div className="flex flex-wrap items-center gap-4"><Button asChild><Link href="/requisitos">{t("home.checkRequirements")}<ArrowUpRight size={20} strokeWidth={1.75} aria-hidden="true" /></Link></Button><a className="t-small inline-flex min-h-12 items-center gap-2 text-brand underline underline-offset-4" href="https://www.iatatravelcentre.com/" target="_blank" rel="noopener noreferrer">IATA Travel Centre<ArrowUpRight size={16} strokeWidth={1.75} aria-hidden="true" /></a></div></div></section>; }

export function FinalCta() { const t = useTranslations(); return <section className="container-site py-14 text-center sm:py-24" aria-labelledby="cta-title"><div className="space-y-6"><h2 id="cta-title" className="t-h2">{t("home.finalTitle")}</h2><p className="t-body-lg text-ink-soft">{t("home.finalBody")}</p><QuoteButton payload={{ service: "Viaje a medida", fields: {} }}>{t("common.whatsapp")}</QuoteButton></div></section>; }
