"use client";

import { Turnstile, useHumanToken } from "@/components/turnstile";
import { trackEvent } from "@/lib/analytics";
import { useTranslations } from "next-intl";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { captureLead, whatsappQuoteHref } from "@/lib/quote";
import { QuoteSuccess } from "@/components/quote/quote-parts";
import { validateContact } from "@/lib/contact-validation";

export function ContactForm() { const t = useTranslations("contact"); const quoteT = useTranslations("quote"); const human = useHumanToken(); const [challenge, setChallenge] = useState(0); const [errors, setErrors] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [status, setStatus] = useState(""); const [href, setHref] = useState(""); const [reference, setReference] = useState(""); const errorMessages: Record<string, string> = { nombre: t("nameError"), email: t("emailError"), mensaje: t("messageError"), telefono: t("phoneError") };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; const form = event.currentTarget; const result = validateContact(Object.fromEntries(new FormData(form))); const localizedErrors = Object.fromEntries(Object.keys(result.errors).map(key => [key, errorMessages[key] || t("error")])); setErrors(localizedErrors); if (Object.keys(localizedErrors).length) { form.querySelector<HTMLElement>(`[name="${Object.keys(localizedErrors)[0]}"]`)?.focus(); return; } setStatus(""); let turnstileToken: string; try { turnstileToken = await human.ensure(); } catch { setStatus(t("error")); return; } setBusy(true); const payload = { turnstileToken, service: "Contacto", servicio: "contacto", fields: { Nombre: result.values.nombre, Email: result.values.email, Teléfono: result.values.telefono, Notas: result.values.mensaje }, formData: result.values }; try { const { referencia } = await captureLead(payload); trackEvent("contact_submit", { service: "contacto", status: "saved" }); setReference(referencia); setHref(whatsappQuoteHref(payload, referencia)); setStatus(t("saved")); } catch { setStatus(t("error")); } finally { setBusy(false); setChallenge(value => value + 1); } }
  if (href) return <QuoteSuccess result={{ referencia: reference, href }} service="contacto" />;
  const fields = [{ name: "nombre", label: t("name"), type: "text", max: 120 }, { name: "email", label: t("email"), type: "email", max: 254 }, { name: "telefono", label: t("phone"), type: "tel", max: 40 }, { name: "mensaje", label: t("message"), type: "textarea", max: 3000 }] as const;
  return <form onSubmit={submit} noValidate className="space-y-6" aria-busy={busy}><p className="t-small text-ink-soft">{t("requiredFields")}</p><fieldset disabled={busy} className="space-y-6"><div hidden aria-hidden="true"><label htmlFor="contact-website">{t("website")}</label><input id="contact-website" name="website" tabIndex={-1} autoComplete="off" /></div>{fields.map(({ name, label, type, max }) => <div key={name} className="space-y-2"><label className="t-small block" htmlFor={`contact-${name}`}>{label}{name !== "telefono" ? " *" : ""}</label>{type === "textarea" ? <textarea id={`contact-${name}`} name={name} required rows={6} maxLength={max} className="t-body w-full resize-y rounded-btn border border-line bg-canvas px-3 py-2 focus-visible:border-brand aria-invalid:border-error" aria-invalid={!!errors[name]} aria-describedby={errors[name] ? `contact-${name}-error` : undefined} /> : <Input id={`contact-${name}`} name={name} type={type} required={name !== "telefono"} maxLength={max} autoComplete={name === "nombre" ? "name" : name === "telefono" ? "tel" : "email"} aria-invalid={!!errors[name]} aria-describedby={errors[name] ? `contact-${name}-error` : undefined} />}{errors[name] && <p id={`contact-${name}-error`} className="t-small text-error">{errors[name]}</p>}</div>)}<Turnstile onToken={human.onToken} resetKey={challenge} /><Button type="submit" disabled={busy || human.verifying} aria-busy={busy || human.verifying}>{busy ? t("saving") : human.verifying ? quoteT("verifying") : t("send")}</Button></fieldset>{status && <p role="alert" className="text-error">{status}</p>}</form>;
}
